### ISSUE TITLE
Python 3 compatible?

### ISSUE THREAD

**Issue by anurag90x** [dlanger/nose-parallel#10]
Is nose-parallel python 3 compatible? Running the tests with python 3 indicates that it is. If so, can the the lib be updated to publish a universal wheel? I'd be happy to do this.

**Comment by dlanger** [comment]
It should be. If you send a PR with the right settings for (I think) `setup.cfg` to generate one, I'd be happy to merge and release this evening.

**Comment by rolandk-nearpod** [comment]
Just checking to see if an universal wheel was created for Python 3?
