### ISSUE TITLE
Useable with Django?

### ISSUE THREAD

**Issue by ianwalter** [dlanger/nose-parallel#4]
Do you know if I would be able to use this with Django?
I run my command using something like `python ./manage.py test` but if I add `--with-parallel` manage.py complains about it not being an option.

**Comment by dlanger** [comment]
I've used it with Django without issue. 

Which version of Django are on you? Do you also have `django-nose` installed?

**Comment by ianwalter** [comment]
Hmm, I'm using Django 1.6 and django-nose 1.2

**Comment by dlanger** [comment]
Are you still having issues with this, or did you move on?

**Comment by ianwalter** [comment]
I ended up putting this on hold. I'll report back when I pick it up again and figure out the issue, thanks!
