### ISSUE TITLE
balance tests by timing

### ISSUE THREAD

**Issue by oppianmatt** [dlanger/nose-parallel#6]
Using this plugin can lead to some unbalanced runners. For example I have one that completes in about 200 seconds and the other in 800 seconds.

It would be nice if it could use a previous run, perhaps the xunit format, to balance the test splits so the timings are roughly equal.

**Comment by kouk** [comment]
@oppianmatt I had a similar problem, now using the code in #5, which on average across builds balances things out. Then again, sometimes you may be unlucky and the "random" distribution doesn't help. But on average things will be better I believe.

**Comment by oppianmatt** [comment]
yep saw that PR, that will help. You mention circleci and they seem to have it for their nose: https://circleci.com/blog/announcing-automatic-test-balancing/

**Comment by dlanger** [comment]
Using CircleCI's balancing is a better bet at this point - they can save the output of each test run and balance using that. 

Now that their game is much better, this plugin is best used on CI systems which don't do this for you.
